import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // Puedes elegir los pesos que necesites
});

export const metadata = {
  title: "Leave request dashbord",
  description: "Generated by Jose Manuel Osorio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
